### PR TITLE
Added "addRss" feature - and some minor changes 

### PR DESCRIPTION
**Pull request by DimaBroi**

### CODE REVIEW

**Comment by DimaBroi** [comment]
@noam09 any idea when you plan to take a look on my PR

**Comment by noam09** [comment]
Hey @DimaBroi, really sorry for the delay. I've been overloaded with work, I hope to go over this over the weekend.

**Review by noam09 — COMMENTED** [review]
Hey @DimaBroi, this feature really looks great. 

A few small points to consider:

* ~~In `add_rss()`, `enable_plugin` is called to enable YaRSS2. Is there a check leading up to this point which makes sure that YaRSS2 is indeed an installed plugin? Maybe a check for the plugin's availability should be made right before enabling, and if it isn't available we can send the user a message suggesting that the plugin should be installed first. This check should ideally come at the earliest point in which the user selects any RSS-related option.~~
  Just noticed the check in `add()`
* I noticed you removed `self.core = component.get('Core')` - was there a particular reason for this?
* Maybe use a `pycodestyle` linter with your IDE to achieve similar code style to that used in the current code.
* **EDIT:** I seem to be getting a KeyError for "regex_exp" when the default (empty) RSS text fields are saved. Might need to check for `config["regex_exp"]` existing before accessing its items. 
* **EDIT 2:** When no RSS feeds are found, maybe send a message to the user so he/she knows none were found. Alternatively (in the future), maybe add the ability to add a new RSS feed URL via Telegramer. :)

I'll test out the RSS features on a clean install as well and come back with some more specific feedback. 

Thanks again for the contribution. :+1:

**Comment by DimaBroi** [comment]
> I noticed you removed self.core = component.get('Core') - was there a particular reason for this?


I thought that as the component holds such big structure there is no point to have another one - unless of course it collects it all again from the files when we do `component.get('Core')` -   pls advice on that issue.

**Comment by DimaBroi** [comment]
> EDIT 2: When no RSS feeds are found, maybe send a message to the user so he/she knows none were found. 

I have checked it at `prepare_rss_feed` , but I have sent the wrong msg - just fixed it,

>Alternatively (in the future), maybe add the ability to add a new RSS feed URL via Telegramer. :)

Totally a feature :)

**Comment by noam09** [comment]
Hey @DimaBroi, sorry for the tremendous delay. I'm in the process of merging all pull requests to the `develop` branch for beta releases. If everything is working fine, please change the merge destination to the `develop` branch and I'll merge it in. Thanks again!

**Comment by DimaBroi** [comment]
Hi @noam09 
last time I used it was working...
I moved it to develop .

**Pull request closed without merging**
