### PR TITLE
Proxy support

### PR DESCRIPTION
**Pull request by Tan4ek**
Proxy support from [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy)
For socks support I've put `socks.py` and `sockshandler.py` from [PySocks](https://github.com/Anorov/PySocks) library in `include` directory directly.

Screenshot_20190319_000300
Screenshot_20190319_000157

### CODE REVIEW

**Comment by noam09** [comment]
Hi @Tan4ek! Thank you for your contribution. I'll go over this ASAP. :)

**Comment by noam09** [comment]
I noticed you're using [this version](https://github.com/Anorov/PySocks/blob/1e1d5bd3d81d09a0a7920515307dea38bcaa9b97/socks.py) of `socks.py`. Any reason not to use the [latest version](https://github.com/Anorov/PySocks/blob/master/socks.py)?

**Comment by Tan4ek** [comment]
No there isn't.

**Comment by noam09** [comment]
Okay great, if [this version](https://github.com/Anorov/PySocks/blob/master/socks.py) works when you test it, please push a change with the latest file.

**Comment by Tan4ek** [comment]
I tested with last version from [PySocks/master last commit](https://github.com/Anorov/PySocks/blob/d2aea5a9c27dece82226eb90a10d4fef286044e2/socks.py) it's working well

**Comment by noam09** [comment]
~Hey @Tan4ek, I'm trying out the proxy functionality using `socks5://127.0.0.1:9150` (with Tor running on `locahost`), and for some reason it appears that at least some of the traffic going out to `api.telegram.org` isn't being tunneled. How would you go about debugging this?~
EDIT: My bad, I was sniffing all interfaces, which included the loopback traffic.

**Pull request merged**
